eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
okta:
  oauth2:
    issuer: https://dev-71716389.okta.com/oauth2/default
    audience: api://default
#   client-id: 0oa8vx8vut76NPyT95d7
#   client-secret: aZ0h836vkahyUDcqHCTp_FO3uEYpncOTeX20xRlk
#   scopes: openid, profile, email
spring:
  zipkin:
    baseUrl: http://localhost:9411
