eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
#okta:
#  oauth2:
#   issuer: https://dev-95079793.okta.com/oauth2/default
#   audience: api://default
#   client-id: 0oa8vfrd4gsG9xbt25d7
#   client-secret: u7gnyOcpwSjKz0lWD3l7EdVaFD9f36s3LOujJ_7i
#   scopes: openid, profile, email
spring:
  zipkin:
    baseUrl: http://localhost:9411
